# Secrets

keys:
  - &gustav age19c8qem9840j93me4qauxkxxkuayejgvck2l7yu8z8r3ffd0wr9jq2hy70c
  - &superdator age1l9rlv0kltyh42f3t0hlmpulxkuez00dumw24w8ygw09497wea35q4ecgw8
  - &murphy age1d2pp6nj96az2rzdddhghfsvvnl40fdrtmmfw2em5hfpuj2ja5sjqjhvrn2
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *gustav
          - *superdator
  - path_regex: secrets/ros2.yaml$
    key_groups:
      - age:
          - *gustav
          - *murphy
